servers = [
    # Ubuntu Server
    ('Ubuntu Server', '22.04'), 
    ('Ubuntu Server', '21.04'),
    ('Ubuntu Server', '20.04'), 
    ('Ubuntu Server', '18.04'), 
    ('Ubuntu Server', '16.04'), 
    ('Ubuntu Server', '14.04'), 
    ('Ubuntu Server', '12.04'), 
    ('Ubuntu Server', '10.04'),
    ('Ubuntu Server', '8.04'), 
    ('Ubuntu Server', '6.06'),

    # Windows Server
    ('Windows Server', '2022'), 
    ('Windows Server', '2019'), 
    ('Windows Server', '2016'), 
    ('Windows Server', '2012'), 
    ('Windows Server', '2008'), 
    ('Windows Server', '2003'), 
    ('Windows Server', '2000'), 
    ('Windows Server', 'NT 4.0'), 
    ('Windows Server', 'NT 3.51'), 
    ('Windows Server', 'NT 3.5'),

    # Red Hat Enterprise Linux Server
    ('Red Hat Enterprise Linux Server', '8.4'), 
    ('Red Hat Enterprise Linux Server', '8.3'), 
    ('Red Hat Enterprise Linux Server', '8.2'), 
    ('Red Hat Enterprise Linux Server', '8.1'), 
    ('Red Hat Enterprise Linux Server', '7.9'), 
    ('Red Hat Enterprise Linux Server', '7.8'), 
    ('Red Hat Enterprise Linux Server', '7.7'), 
    ('Red Hat Enterprise Linux Server', '7.6'), 
    ('Red Hat Enterprise Linux Server', '6.10'), 
    ('Red Hat Enterprise Linux Server', '6.9'), 
    ('Red Hat Enterprise Linux Server', '6.8'), 
    ('Red Hat Enterprise Linux Server', '6.7'), 
    ('Red Hat Enterprise Linux Server', '5.11'), 
    ('Red Hat Enterprise Linux Server', '5.10'), 
    ('Red Hat Enterprise Linux Server', '5.9'), 
    ('Red Hat Enterprise Linux Server', '5.8'), 

    # CentOS
    ('CentOS', '8'), 
    ('CentOS', '7'), 
    ('CentOS', '6'), 
    ('CentOS', '5'), 
    ('CentOS', '4'), 
    ('CentOS', '3'), 
    ('CentOS', '2'),

    # Debian
    ('Debian', '11'), 
    ('Debian', '10'), 
    ('Debian', '9'), 
    ('Debian', '8'),
    ('Debian', '7'),
    ('Debian', '6'),
    ('Debian', '5'),
    ('Debian', '4'),
    ('Debian', '3'),

    # Fedora Server
    ('Fedora Server', '35'),
    ('Fedora Server', '34'),
    ('Fedora Server', '33'),
    ('Fedora Server', '32'),
    ('Fedora Server', '31'),
    ('Fedora Server', '30'),

    # SUSE Linux Enterprise Server
    ('SUSE Linux Enterprise Server', '15'),
    ('SUSE Linux Enterprise Server', '12'),
    ('SUSE Linux Enterprise Server', '11'),
    ('SUSE Linux Enterprise Server', '10'),
    ('SUSE Linux Enterprise Server', '9'),
    ('SUSE Linux Enterprise Server', '8'),
    ('SUSE Linux Enterprise Server', '7'),

    # Arch Linux
    ('Arch Linux', '2023.08'),
    ('Arch Linux', '2023.04'),
    ('Arch Linux', '2022.11'),
    ('Arch Linux', '2022.06'),
    ('Arch Linux', '2022.01'),
    ('Arch Linux', '2021.11'),

    # Gentoo
    ('Gentoo', '2023.07'),
    ('Gentoo', '2023.03'),
    ('Gentoo', '2022.09'),
    ('Gentoo', '2022.03'),
    ('Gentoo', '2021.07'),

    # FreeBSD
    ('FreeBSD', '13.0'),
    ('FreeBSD', '12.2'),
    ('FreeBSD', '11.4'),
    ('FreeBSD', '10.4'),
    ('FreeBSD', '9.3'),
    ('FreeBSD', '8.4'),
    ('FreeBSD', '7.4'),
    ('FreeBSD', '6.4'),
    ('FreeBSD', '5.5'),

    # OpenBSD
    ('OpenBSD', '7.0'),
    ('OpenBSD', '6.9'),
    ('OpenBSD', '6.8'),
    ('OpenBSD', '6.7'),
    ('OpenBSD', '6.6'),
    ('OpenBSD', '6.5'),
    ('OpenBSD', '6.4'),
    ('OpenBSD', '6.3'),
    ('OpenBSD', '6.2'),
    ('OpenBSD', '6.1'),
    ('OpenBSD', '6.0')
]


peripherals = [
    ('Computer', 1000), 
    ('Laptop', 1500), 
    ('Monitor', 200), 
    ('Printer', 300), 
    ('Scanner', 250), 
    ('Projector', 500),
    ('Router', 150),
    ('Switch', 100),
    ('Firewall', 700),
    ('Wireless Access Point', 120),
    ('NAS Device', 800),
    ('Keyboard', 50),
    ('Mouse', 30),
    ('Headphones', 100),
    ('Speakers', 150),
    ('Webcam', 80),
    ('Microphone', 70),
    ('External Hard Drive', 250),
    ('USB Flash Drive', 20),
    ('External SSD', 180),
    ('Bluetooth Adapter', 15),
    ('Ethernet Cable', 10),
    ('Wi-Fi USB Adapter', 30),
    ('HDMI Cable', 15),
    ('VGA Cable', 20),
    ('DVI Cable', 25),
    ('DisplayPort Cable', 35),
    ('USB Type-C Cable', 40),
    ('Printer Paper (500 sheets)', 5),
    ('Ink Cartridge (Black)', 40),
    ('Ink Cartridge (Color)', 50),
    ('Wireless Keyboard', 60),
    ('Wireless Mouse', 40),
    ('Gaming Mouse', 70),
    ('Gaming Keyboard', 80),
    ('Gaming Headset', 100),
    ('Gaming Monitor', 250),
    ('Ultra-Wide Monitor', 400),
    ('4K Monitor', 600),
    ('Color Laser Printer', 400),
    ('All-in-One Printer', 200),
    ('3D Printer', 800),
    ('Portable Scanner', 120),
    ('Home Projector', 300),
    ('Network Attached Storage (12TB)', 800),
    ('Network Attached Storage (4TB)', 300),
    ('Managed Gigabit Switch', 200),
    ('10 Gigabit Ethernet Switch', 800),
    ('Wireless Mesh Router', 150),
    ('Enterprise Firewall', 5000),
    ('Powerline Ethernet Adapter', 70),
    ('Wi-Fi Range Extender', 50),
    ('Graphics Tablet', 200),
    ('Graphics Card', 600),
    ('External Graphics Enclosure', 250),
    ('Smartphone Tripod Mount', 20),
    ('Portable Power Bank', 40),
    ('Wireless Charging Pad', 30),
    ('USB Hub', 25),
    ('USB-C Docking Station', 120),
    ('Thunderbolt Dock', 200),
    ('UPS (Uninterruptible Power Supply)', 200),
    ('Cable Organizer', 10),
    ('Wireless Presenter Remote', 30),
    ('USB Desk Fan', 15),
    ('Desk Lamp with Wireless Charger', 50),
    ('Bluetooth Earbuds', 80),
    ('Wireless Noise-Canceling Headphones', 300),
    ('Wireless Gaming Controller', 70),
    ('External DVD Drive', 40),
    ('Wi-Fi Smart Plug', 20),
    ('Smart Home Security Camera', 100),
    ('Smart Bulb', 25),
    ('Portable Bluetooth Speaker', 60),
    ('Smartwatch', 150),
    ('Fitness Tracker', 100),
    ('VR Headset', 400),
    ('Video Capture Card', 150),
    ('Power Strip with USB Ports', 30),
    ('Wireless Presentation Clicker', 40),
    ('Digital Voice Recorder', 50),
    ('Portable SSD', 120),
    ('MIDI Controller', 250),
    ('USB Condenser Microphone', 100),
    ('Noise-Canceling Earbuds', 150),
    ('Ergonomic Mouse Pad', 20),
    ('High-End Graphics Workstation', 30000),
    ('Enterprise Data Storage System', 80000),
    ('Professional Video Editing Setup', 50000),
    ('High-Performance Gaming PC', 10000),
    ('Broadcast-quality Studio Microphone', 1500),
    ('Ultra-High-Resolution Studio Monitor', 3000),
    ('Large Format Photo Printer', 12000),
    ('High-End Graphics Card (Workstation)', 8000),
    ('Professional 3D Printing System', 50000),
    ('Industrial-grade 3D Scanner', 35000),
    ('Ultra-Wide Curved Monitor', 2000),
    ('Gigabit Network Switch (Enterprise)', 5000),
    ('Enterprise-Grade Firewall Appliance', 10000),
    ('Advanced Network Security System', 70000),
    ('Professional Video Production Camera', 15000),
    ('High-Capacity Enterprise Network Storage', 80000),
    ('High-Performance Wireless Access Point', 3000)
]


services = [
    ('HTTP', '1.1'), 
    ('HTTP', '2.0'), 
    ('HTTP', '3.0'), 
    ('FTP', '1.0'), 
    ('SMTP', '1.0'), 
    ('IMAP', '4'), 
    ('SSH', '2.0'), 
    ('SSH', '1.99'), 
    ('SSH', '1.5'), 
    ('DNS', '1.0'),
    ('LDAP', '3'),
    ('LDAP', '2'),
    ('RDP', '10'),
    ('RDP', '8'),
    ('RDP', '7'),
    ('RDP', '6'),
    ('POP3', '3'),
    ('POP3', '2'),
    ('SNMP', '3'),
    ('SNMP', '2c'),
    ('SNMP', '1'),
    ('SMTPS', '1.0'),
    ('FTPS', '1.0'),
    ('SFTP', '3.0'),
    ('SMB', '3'),
    ('SMB', '2'),
    ('SMB', '1'),
    ('NFS', '4'),
    ('NFS', '3'),
    ('NFS', '2'),
    ('NTP', '4'),
    ('NTP', '3'),
    ('LDAP over SSL', '3'),
    ('LDAP over TLS', '3'),
    ('LDAPS', '3'),
    ('DNSSEC', '1.0'),
    ('DOH (DNS over HTTPS)', '1.0'),
    ('DOQ (DNS over QUIC)', '1.0'),
    ('SNTP', '4'),
    ('SNTP', '3'),
    ('SNTP', '2'),
    ('SNTP', '1'),
    ('RADIUS', '3'),
    ('RADIUS', '2'),
    ('RADIUS', '1'),
    ('DHCP', '6'),
    ('DHCP', '4'),
    ('DHCP', '3'),
    ('BGP', '5'),
    ('BGP', '4'),
    ('BGP', '3'),
    ('LDAP over UDP', '3'),
    ('LDAP over TCP', '3'),
    ('Telnet', '2'),
    ('Telnet', '1'),
    ('SIP', '2'),
    ('SIP', '1'),
    ('XMPP', '1.0'),
    ('XMPP', '0.9'),
    ('Kerberos', '5'),
    ('Kerberos', '4'),
    ('Kerberos', '3'),
    ('Kerberos', '2'),
    ('Kerberos', '1'),
    ('NIS', '3'),
    ('NIS', '2'),
    ('NIS', '1'),
    ('TFTP', '2'),
    ('TFTP', '1'),
    ('IPsec', '3'),
    ('IPsec', '2'),
    ('IPsec', '1'),
    ('HTTPS', '1.1'),
    ('SMB over TCP', '3'),
    ('SMB over NetBIOS', '3'),
    ('SMB over NetBEUI', '3'),
    ('SCP', '2'),
    ('SCP', '1'),
    ('SFTP', '6'),
    ('SFTP', '5'),
    ('SFTP', '4'),
    ('SNMPv3 Trap', '3'),
    ('SNMPv2 Trap', '2'),
    ('SNMPv1 Trap', '1'),
    ('RIP', '2'),
    ('RIP', '1'),
    ('EIGRP', '5'),
    ('EIGRP', '4'),
    ('EIGRP', '3'),
    ('EIGRP', '2'),
    ('EIGRP', '1'),
    ('BGP4+', '4'),
    ('BGP4+', '3'),
    ('BGP4+', '2'),
    ('BGP4+', '1'),
    ('OSPFv3', '3'),
    ('OSPFv3', '2'),
    ('OSPFv3', '1'),
    ('OSPFv2', '2'),
    ('OSPFv2', '1'),
    ('OSPFv1', '1'),
    ('IS-IS', '4'),
    ('IS-IS', '3'),
    ('IS-IS', '2'),
    ('IS-IS', '1'),
    ('RIPv2', '2'),
    ('RIPv2', '1'),
    ('HSRP', '2'),
    ('HSRP', '1'),
    ('VRRP', '3'),
    ('VRRP', '2'),
    ('VRRP', '1'),
    ('GLBP', '3'),
    ('GLBP', '2'),
    ('GLBP', '1'),
    ('IGMP', '3'),
    ('IGMP', '2'),
    ('IGMP', '1'),
    ('PIM', '2'),
    ('PIM', '1'),
    ('DVMRP', '3'),
    ('DVMRP', '2'),
    ('DVMRP', '1'),
    ('SLP', '2'),
    ('SLP', '1'),
    ('LLMNR', '2'),
    ('LLMNR', '1'),
    ('mDNS', '1.0'),
    ('mDNS', '0.9'),
    ('SSDP', '2'),
    ('SSDP', '1'),
    ('NetBIOS', '3'),
    ('NetBIOS', '2'),
    ('NetBIOS', '1'),
    ('SNMP Trap', '2'),
    ('SNMP Trap', '1'),
    ('SSDP over UDP', '2'),
    ('SSDP over UDP', '1'),
    ('XDMCP', '4'),
    ('XDMCP', '3'),
    ('XDMCP', '2'),
    ('XDMCP', '1'),
    ('RPC', '2'),
    ('RPC', '1'),
    ('CIFS', '1'),
    ('AFP', '3'),
    ('AFP', '2'),
    ('AFP', '1'),
    ('BACnet', '3'),
    ('BACnet', '2'),
    ('BACnet', '1'),
    ('WINS', '3'),
    ('WINS', '2'),
    ('WINS', '1'),
    ('RADSEC', '3'),
    ('RADSEC', '2'),
    ('RADSEC', '1'),
    ('RADIUS Accounting', '3'),
    ('RADIUS Accounting', '2'),
    ('RADIUS Accounting', '1'),
    ('TACACS+', '2'),
    ('TACACS+', '1'),
    ('NetFlow', '10'),
    ('NetFlow', '9'),
    ('NetFlow', '8'),
    ('NetFlow', '7'),
    ('NetFlow', '6'),
    ('NetFlow', '5'),
    ('NetFlow', '4'),
    ('NetFlow', '3'),
    ('NetFlow', '2'),
    ('NetFlow', '1'),
    ('IPFIX', '10'),
    ('IPFIX', '9'),
    ('IPFIX', '8'),
    ('IPFIX', '7'),
    ('IPFIX', '6'),
    ('IPFIX', '5'),
    ('IPFIX', '4'),
    ('IPFIX', '3'),
    ('IPFIX', '2'),
    ('IPFIX', '1'),
    ('sFlow', '5'),
    ('sFlow', '4'),
    ('sFlow', '3'),
    ('sFlow', '2'),
    ('sFlow', '1'),
    ('NetFlow-Lite', '1'),
    ('CDP', '3'),
    ('CDP', '2'),
    ('CDP', '1'),
    ('LLDP', '802.1ab'),
    ('LLDP', '802.1ab-d2005'),
    ('LLDP', '802.1ab-2005'),
    ('UPnP', '2'),
    ('UPnP', '1'),
    ('NetBIOS Name Service', '3'),
    ('NetBIOS Name Service', '2'),
    ('NetBIOS Name Service', '1'),
    ('NetBIOS Datagram', '3'),
    ('NetBIOS Datagram', '2'),
    ('NetBIOS Datagram', '1'),
    ('NetBIOS Session', '3'),
    ('NetBIOS Session', '2'),
    ('NetBIOS Session', '1'),
    ('DHCPv6', '1'),
    ('RIPng', '1'),
    ('OSPFv3', '1'),
    ('LACP', '1'),
    ('LLDP-MED', '1'),
    ('iSCSI', '1'),
    ('FCoE', '1'),
    ('FCIP', '1'),
    ('NVMe-over-Fabrics', '1'),
    ('SAS', '1'),
    ('iWARP', '1'),
    ('RoCE', '1'),
    ('MPLS', '1'),
    ('GRE', '1'),
    ('VXLAN', '1'),
    ('L2TP', '1'),
    ('PPTP', '1'),
    ('PPP', '1'),
    ('IKEv2', '1'),
    ('L2TPv3', '1'),
    ('EAP', '1'),
    ('RADIUS Change of Authorization (CoA)', '1'),
    ('DIAMETER', '1'),
    ('Diameter Credit Control Application', '1'),
    ('SCTP', '1'),
    ('SIP-T', '1'),
    ('H.323', '1'),
    ('H.248', '1'),
    ('MGCP', '1'),
    ('RSTP', '1'),
    ('MSTP', '1'),
    ('FDDI', '1'),
    ('ATM', '1'),
    ('X.25', '1'),
    ('Frame Relay', '1'),
    ('SDH', '1'),
    ('SONET', '1'),
    ('HDLC', '1'),
    ('PPP Multilink', '1'),
    ('LAPB', '1'),
    ('X.21', '1'),
    ('VLAN Trunking Protocol (VTP)', '1'),
    ('STP', '1'),
    ('DTP', '1'),
    ('PortFast', '1'),
    ('BPDU Guard', '1'),
    ('Root Guard', '1'),
    ('Loop Guard', '1'),
    ('EtherChannel', '1'),
    ('Link Aggregation Control Protocol (LACP)', '1'),
    ('PPP Multilink Group', '1'),
    ('Multicast VLAN Registration (MVR)', '1'),
    ('L2TPv3', '1'),
    ('L2TPv2', '1'),
    ('L2TPv1', '1'),
    ('VXLAN', '1'),
    ('NHRP', '1'),
    ('H-VPLS', '1'),
    ('A-VPLS', '1'),
    ('EVPN', '1'),
    ('HSRP', '1'),
    ('VRRP', '1'),
    ('GLBP', '1'),
    ('BFD', '1'),
    ('Cisco IP SLA', '1'),
    ('IP SLA', '1'),
    ('NetFlow', '1'),
    ('sFlow', '1'),
    ('SNMP', '1'),
    ('CDP', '1'),
    ('LLDP', '1'),
    ('UPnP', '1'),
    ('NetBIOS Name Service', '1'),
    ('NetBIOS Datagram', '1'),
    ('NetBIOS Session', '1')
]

long_wordlist = [
    "apple", "banana", "orange", "grape", "cherry", "strawberry",
    "kiwi", "mango", "watermelon", "pineapple", "blueberry", "raspberry",
    "peach", "pear", "apricot", "plum", "lemon", "lime", "coconut",
    "avocado", "blackberry", "cantaloupe", "fig", "guava", "honeydew",
    "jackfruit", "kumquat", "mangosteen", "nectarine", "olive", "papaya",
    "quince", "rhubarb", "soursop", "tangerine", "ugli fruit", "vanilla",
    "watercress", "yuzu", "zucchini", "apricot", "blueberry", "cherry",
    "date", "elderberry", "fig", "grapefruit", "huckleberry", "kiwifruit",
    "lemon", "mango", "nectarine", "orange", "papaya", "quince", "raspberry",
    "strawberry", "tangerine", "ugli fruit", "victory apple", "wolfberry",
    "yellow passionfruit", "zinfandel grape", "almond", "cashew", "hazelnut",
    "pecan", "pistachio", "walnut", "carrot", "broccoli", "cauliflower",
    "cucumber", "potato", "tomato", "pumpkin", "eggplant", "asparagus",
    "artichoke", "watermelon", "blueberry", "blackberry", "cantaloupe",
    "kiwifruit", "raspberry", "peach", "pear", "guava", "tamarind", "guava",
    "cantaloupe", "mango", "kiwifruit", "apricot", "plum", "blackcurrant",
    "lychee", "dragon fruit", "passion fruit", "pomegranate", "gooseberry",
    "loganberry", "kiwi", "rambutan", "soursop", "star fruit", "tamarillo",
    "ugli fruit", "yuzu", "zucchini", "honeydew", "cherry", "grapefruit",
    "persimmon", "papaya", "apricot", "pear", "kale", "spinach", "lettuce",
    "arugula", "collard greens", "swiss chard", "bok choy", "beet greens",
    "mustard greens", "turnip greens", "dandelion greens", "watercress"
]
